#!/bin/sh
n=ens33
R1=`cat /sys/class/net/$n/statistics/rx_bytes`
T1=`cat /sys/class/net/$n/statistics/tx_bytes`
sleep 1
R2=`cat /sys/class/net/$n/statistics/rx_bytes`
T2=`cat /sys/class/net/$n/statistics/tx_bytes`
RBPS=`expr $R2 - $R1`
TBPS=`expr $T2 - $T1`

RMBPS=$(echo "scale=2; $RBPS / 1024.0 / 1024.0" | bc)
TMBPS=$(echo "scale=2; $TBPS / 1024.0 / 1024.0" | bc)

printf "%.2fM ⇵ %.2fM" $RMBPS $TMBPS