#!/bin/sh
R1=`cat /sys/class/net/ens33/statistics/rx_bytes`
T1=`cat /sys/class/net/ens33/statistics/tx_bytes`
sleep 1
R2=`cat /sys/class/net/ens33/statistics/rx_bytes`
T2=`cat /sys/class/net/ens33/statistics/tx_bytes`
RBPS=`expr $R2 - $R1`
TBPS=`expr $T2 - $T1`

RMBPS=$(echo "scale=2; $RBPS / 1024.0 / 1024.0" | bc)
TMBPS=$(echo "scale=2; $TBPS / 1024.0 / 1024.0" | bc)

echo ~/Documents/tint2configs/executors/net.svg
printf "%.2f:%.2f M" $RMBPS $TMBPS